a = 'DLLDLDLLLLLDLLLLRLDLLDLD\
LLLRRDLLLLRDLLLLLDLLRLRR\
RDLLLDLLLDLLLLLDLLRDLLLR\
RLDLLLDLLLLLDLLLRLDLLDLL\
RLRRDLLLDLLRLRRRDLLRDLLL\
LLDLLLRLDLLDLLRLRRDLLLLL\
DLLRDLLLRRLDLLLDLLLLLDLL\
RDLLRLRRDLLLDLLLDLLRLRRR\
DLLLLLDLLLLRLDLLLRRLRRDD\
LLLRRDLLLRRLRDLLLRLDLRRD\
DLLLRLDLLLRRRDLLRLRRRDLRRLD'
print(len(a))
